"""Add activations_per_frame to creature_frames

Revision ID: 56f5a434d092
Revises: 004
Create Date: 2026-01-24 21:17:59.758745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f5a434d092'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creature_frames', sa.Column('activations_per_frame', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_creatures_run_id'), 'creatures', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creatures_run_id'), table_name='creatures')
    op.drop_column('creature_frames', 'activations_per_frame')
    # ### end Alembic commands ###
